import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import styles from "./layout.module.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='dark'>
      <body className={styles.grid}>
        <Providers>
          <aside>
            <h1>Sidebar</h1>
          </aside>
          <main>
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
