name: Build on Windows

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # use the Node.js version your project requires

    - name: Install dependencies
      run: npm install
      working-directory: ./front-end

    - name: Build the project
      run: npm run build
      working-directory: ./front-end

    - name: Build Electron app for Windows
      run: |
        npm run make
        ls -la front-end/out/make/squirrel.windows/x64
      working-directory: ./front-end

    - name: Upload artifact to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: front-end/out/make/squirrel.windows/x64/simple-pos Setup-1.0.0.exe
        asset_name: simple-pos.exe
        asset_content_type: application/x-msdownload
