name: Build on Windows

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # use the Node.js version your project requires

    - name: Install dependencies
      run: npm install
      working-directory: ./front-end

    - name: Build the project
      run: npm run build
      working-directory: ./front-end

    - name: Build Electron app for Windows
      run: npm run make
      working-directory: ./front-end

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-app
        path: front-end/out/make/squirrel.windows/x64/  # adjust this path to match the output directory of your Windows build
